


### récupérer tous les gunplas 
GET http://localhost:3002/gunplas HTTP/1.1
Content-Type: application/json

### récupérer un gunpla avec son id
GET http://localhost:3002/fichegunpla/66255e562c350876b3f3fb91 HTTP/1.1
Content-Type: application/json

### créer un gunpla

POST http://localhost:3002/gunplas HTTP/1.1
Content-Type: application/json

{
    "title" : "random gundam"
}

### modifier un gunpla

PATCH http://localhost:3002/fichegunpla/65ea3cc5cfbe1c7c009866a8 HTTP/1.1
Content-Type: application/json

{
    "title" : "gundam unicorn"
}

### supprimer un gunpla

DELETE http://localhost:3002/fichegunpla/65ea3da2d5b1ef4521f0b8c7
Content-Type: application/json